name: rby1_pick_pnp_horizon450
description: Pick/PnP 10-episode test with a 450-step task horizon.

extends: rby1_eval.yaml

paths:
  output_base_dir: /u/xna8aw/workspace/live-robotics-lab/LRL_project/MolmoBot/MolmoBot/eval_output/experiments/rby1_pick_pnp_horizon450

tasks:
  - pick
  - pnp

indices:
  - 10
  - 21
  - 33
  - 56
  - 58
  - 74
  - 99
  - 101
  - 123
  - 137

eval:
  task_horizon_steps: 450
  terminate_upon_success: true

policy_env: {}
