name: rby1_pick_pnp_expansion
description: Pick/PnP expansion run for MolmoBot-RBY1Multitask.

extends: rby1_eval.yaml

paths:
  output_base_dir: /u/xna8aw/workspace/live-robotics-lab/LRL_project/MolmoBot/MolmoBot/eval_output/baseline/rby1_pick_pnp_expansion

tasks:
  - pick
  - pnp

indices:
  - 10
  - 21
  - 33
  - 56
  - 58
  - 74
  - 99
  - 101
  - 123
  - 137
  - 155
  - 158
  - 171
  - 199
  - 206
  - 224
  - 230
  - 255
  - 268
  - 279
  - 291
  - 304
  - 318
  - 334
  - 354
  - 361
  - 384
  - 388
  - 413
  - 420
  - 438
  - 447
  - 470
  - 472
  - 488
  - 504
  - 521
  - 533
  - 546
  - 566
  - 578
  - 589
  - 600
  - 619
  - 640
  - 649
  - 661
  - 682
  - 687
  - 713
  - 715
  - 729
  - 748
  - 758
  - 782
  - 795
  - 804
  - 821
  - 829
  - 845
  - 866
  - 872
  - 892
  - 900
  - 921
  - 942
  - 947
  - 961
  - 974
  - 986

eval:
  task_horizon_steps: null

policy_env: {}
